-- Equipment seed data.
-- Pattern: DROP + CREATE + INSERT so every dev boot matches this file exactly.
-- New items: append as the next ID, don't renumber.

DROP TABLE IF EXISTS equipment;

CREATE TABLE equipment (
    id         INTEGER PRIMARY KEY NOT NULL,
    name       TEXT    UNIQUE NOT NULL,
    weight_lbs REAL    NOT NULL
);

INSERT INTO equipment (id, name, weight_lbs) VALUES
    (1,  'Baseball Bat',                            2.2),
    (2,  'Basic Pouch',                             0.4),
    (3,  'Bayonet',                                 1),
    (4,  'Bayonet, M1 w/M7 scabard',                1.56),
    (5,  'Belt',                                    0.7),
    (6,  'Belt, pistol M1923',                      0.56),
    (7,  'Bergen',                                  3),
    (8,  'Billy Club',                              0.5),
    (9,  'Binoculars w/case',                       3.5),
    (10, 'Boil In The Bag',                         0.8),
    (11, 'Bum Pack',                                0.7),
    (12, 'Canteen',                                 2.5),
    (13, 'Canteen, M1910',                          3.69),
    (14, 'Cartridge Belt, M1923',                   1.44),
    (15, 'Cartridge Belt, M1937',                   1.88),
    (16, 'Crowbar',                                 2.5),
    (17, 'D-Ration (1 day)',                        0.25),
    (18, 'Entrenching Tool',                        1.5),
    (19, 'Entrenching tool, M1943 w/carrier',       2.94),
    (20, 'Field Dressing',                          0.1),
    (21, 'Field Radio',                             12),
    (22, 'H Harness',                               0.7),
    (23, 'Harness, M1936',                          0.95),
    (24, 'Hammer',                                  1.5),
    (25, 'Hatchet',                                 2.5),
    (26, 'Headset Coms',                            1),
    (27, 'Holster',                                 0.4),
    (28, 'Holster, M1916',                          0.59),
    (29, 'Ice Pick',                                0.2),
    (30, 'Katana',                                  3),
    (31, 'Knife, Bowie',                            1.1),
    (32, 'Knife, Combat',                           0.6),
    (33, 'Knife, Switch Blade',                     0.3),
    (34, 'K-Ration (1 day)',                        2.31),
    (35, 'M14 Toe Popper',                          0.22),
    (36, 'M18A1 Claymore',                          3.5),
    (37, 'Machete',                                 2.4),
    (38, 'Magazine Pouch, M1 carbine',              0.16),
    (39, 'Magazine pouch, M1923 (.45)',             0.13),
    (40, 'Magazine Pouch, SMG (US WW2)',            0.53),
    (41, 'Misc 1.0lbs',                             1),
    (42, 'Misc 0.1lbs',                             0.1),
    (43, 'Misc 0.25lbs',                            0.25),
    (44, 'MRE',                                     1.5),
    (45, 'Pack, M1936',                             1.81),
    (46, 'Pipe, 24"',                               2.2),
    (47, 'Rat Pack (1 day)',                        3.5),
    (48, 'Rock',                                    1.5),
    (49, 'Saber',                                   2.6),
    (50, 'Scimitar',                                3.7),
    (51, 'SNIPERS Harness',                         1.76),
    (52, 'SOBR Assault Vest',                       2.86),
    (53, 'Stick',                                   2),
    (54, 'Tarzan M21 Assault Vest',                 2.2),
    (55, 'Tarzan M22 Assault Vest',                 1.5),
    (56, 'Tarzan M24 Assault Vest',                 1.5),
    (57, 'Tarzan M32 Assault Vest',                 1.5),
    (58, 'Tripod, M1919A4',                         14),
    (59, 'Two by Four',                             3),
    (60, 'Type 56 AK Chest Rig',                    0.89),
    (61, 'Type 56 SKS Chest Rig',                   0.88),
    (62, 'Type 65 Canteen',                         2.6),
    (63, 'Webbing, ALICE',                          6.5),
    (64, 'Webbing, M1956',                          7.4),
    (65, 'Webbing, M1967',                          7.2),
    (66, 'MCI Ration',                              2.6),
    (67, 'MCI Ration (reduced packaging ect)',      2),
    (68, 'LRP Ration',                              0.69),
    (69, 'PRC-25 Radio',                            23.5),
    (70, 'PRC-25 Battery',                          2.86),
    (71, 'Water, 1 quart',                          2),
    (72, 'Bladder (Mil-Spec), 5 quart with cover',  1.5),
    (73, 'Jerry Can, Plastic (20L)',                5),
    (74, 'Jerry Can, Plastic (10L)',                3.4),
    (75, 'Bandolier, 7 pocket',                     0.18),
    (76, 'Canteen, 2 quart colapsable',             0.35),
    (77, 'Canteen, 2 quart with cover and sling',   1.05),
    (78, 'Webbing, WWII',                           7.8),
    (79, 'Wood Axe',                                3.5),
    (80, 'Survival Kit',                            0.88),
    (81, 'IFAK',                                    2.4),
    (82, 'M3 Medic Bag',                            3.9),
    (83, 'M17 Medic Bag',                           12.25),
    (84, 'Tactical Trauma Kit',                     1.15),
    (85, 'Rapid Response Bag',                      2.5),
    (86, 'M39 Medic Bag',                           10),
    (87, 'Surgical Set',                            0.7),
    (88, 'Combat Stretcher, Folding',               15);
